# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d09626f907a2083d0eca72f420ed8e5763396318ee33f8ca17fe11abf65b7af88d07d6a4276c7d32798f242f506b9b25dd54172ffcda383958a201668deefae8

test:
  secret_key_base: f51bc029b6f9d0598ba07479389a8cfdf78af7ff50554eebf7fcf2e6011c2741ac4c33cb3ea4e63986c9230430ed63640f91ec0f0fe0009f8723f3f7d30d5acd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
